### ISSUE TITLE
TIme check is not working. 

### ISSUE THREAD

**Issue by blujeep** [Clark-College-CTEC/team2-final-project#39]
Survey is marked completed if the start date and end date are on the same date. It will show Completed in the Instructor's dashboard even if the time has not yet expired.

1. Create a survey with at least one question
2. Create at team
3. Create a survey instance.
4. Set the start time to current date and the time to 12:00am. 
3. Set the end date to one hour later than the current time.

Results:
After saving the instance, the dashboard shows "Completed" for the survey. View Results and Release Resutls options are shown.
Expected: The survey should show "in progress" status, with only the View Results option.

![completed_beforetime](https://user-images.githubusercontent.com/18266253/26857521-eb793a84-4adf-11e7-8e46-aa228149d917.png)

**Comment by robin5** [comment]
This was caused by time zone not being set to America/los_angelos in the php.ini file.  When php creates a new DatTime object it is set to the current time.  The current time however of Europe/berlin (which is the default of the XAMP install).  the default time is many hours in the future.  This would cause the time set to be already expired.
